language: bash
services: docker

before_script:
  - image="cast-highlight:latest"

script:
  - bash -c 'shopt -s globstar; shellcheck **/*.{sh,bash}'
  - travis_retry docker build -t "$image" alpine

after_script:
  - docker images
