language: bash
services: docker

before_script:
  - image="cast-highlight:latest"
  - test_repo="https://github.com/tidalmigrations/schoolbus.git"

script:
  - bash -c 'shopt -s globstar; shellcheck **/*.sh'
  - travis_retry docker build -t "$image" alpine

after_script:
  - docker images
  - git clone -q "$test_repo" "$HOME/src"
  - docker run --rm -v "$HOME/src":/src cast-highlight:latest cast --skipUpload --sourceDir /src
