steps:
- name: 'google/cloud-sdk:alpine'
  entrypoint: 'bash'
  args:
  - '-eEuo'
  - 'pipefail'
  - '-c'
  - |-
    apk add --update shellcheck && rm -rf /var/chache/apk/*
    shopt -s globstar; shellcheck -o all **/*.sh
    docker build -t ${_DOCKER_IMAGE} .
    git clone ${_TEST_REPO} "$$HOME/src"
    docker run --rm -v "$$HOME/src":/src ${_DOCKER_IMAGE} cast --skipUpload --sourceDir /src
substitutions:
  _DOCKER_IMAGE: cast-highlight:latest
  _TEST_REPO: https://github.com/tidalmigrations/schoolbus.git
