steps:
  - name: 'google/cloud-sdk:alpine'
    entrypoint: 'bash'
    args:
    - '-eEuo'
    - 'pipefail'
    - '-c'
    - |-
      apk add --update shellcheck && rm -rf /var/chache/apk/*
      shopt -s globstar; shellcheck -o all **/*.sh
      docker build -t ${_DOCKER_TEST_IMAGE} .
      git clone ${_TEST_REPO} "$$HOME/src"
      docker run --rm -v "$$HOME/src":/src ${_DOCKER_TEST_IMAGE} cast --skipUpload --sourceDir /src
  - name: 'gcr.io/cloud-builders/docker'
    args: ['run', '--privileged', 'linuxkit/binfmt:v0.7']
    id: 'initialize-qemu'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['buildx', 'create', '--name', 'mybuilder']
    id: 'create-builder'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['buildx', 'use', 'mybuilder']
    id: 'select-builder'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['buildx', 'inspect', '--bootstrap']
    id: 'show-target-build-platforms'
  - name: 'gcr.io/cloud-builders/docker'
    args:
    - 'buildx'
    - 'build'
    - '--platform'
    - '$_DOCKER_BUILDX_PLATFORMS'
    - '-t'
    - 'gcr.io/$PROJECT_ID/cast-highlight:$_DOCKER_IMAGE_TAG'
    - '--push'
    - '.'
    id: 'build-multi-architecture-container-image'
options:
  env:
    - 'DOCKER_CLI_EXPERIMENTAL=enabled'
  options:
    dynamic_substitutions: true

substitutions:
  _DOCKER_TEST_IMAGE: cast-highlight:latest
  _TEST_REPO: https://github.com/tidalmigrations/schoolbus.git
  _DOCKER_BUILDX_PLATFORMS: 'linux/amd64,linux/arm64'
  _DOCKER_IMAGE_TAG: ${BRANCH_NAME/master/latest}
