steps:
  - name: 'koalaman/shellcheck'
    args: ['--enable=all', 'entrypoint.sh']
    id: 'Check entrypoint script'

  - name: 'google/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - '-eEuo'
      - 'pipefail'
      - '-c'
      - |-
        docker run --privileged linuxkit/binfmt:v0.7
        docker buildx create --name mybuilder
        docker buildx use mybuilder
        docker buildx inspect --bootstrap
        docker buildx build \
          --platform=${_DOCKER_BUILDX_PLATFORMS} \
          -t gcr.io/$PROJECT_ID/cast-highlight:$_DOCKER_IMAGE_TAG \
          --push .
    id: 'Build multi-arch container image'

  - name: 'google/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - '-eEuo'
      - 'pipefail'
      - '-c'
      - |-
        git clone ${_TEST_REPO} "$$HOME/src"
        docker run --rm -v "$$HOME/src":/src \
          gcr.io/$PROJECT_ID/cast-highlight:$_DOCKER_IMAGE_TAG \
          cast --skipUpload --sourceDir /src
    id: 'Test container agains test repo'

options:
  env:
    - 'DOCKER_CLI_EXPERIMENTAL=enabled'
  dynamic_substitutions: true

substitutions:
  _TEST_REPO: https://github.com/tidalmigrations/schoolbus.git
  _DOCKER_BUILDX_PLATFORMS: 'linux/amd64,linux/arm64'
  _DOCKER_IMAGE_TAG: ${BRANCH_NAME/master/latest}
